export type Timesheet = {
    id: number,
    employeeid: number,
    weekending: string,
    processed: boolean,
    mgrapproved: boolean,
    usercommitted: boolean,
    totalreghours: number,
    totalovertime: number,
    approvedby: string,
    submittedby: string,
    processedby: string,
    dateprocessed: string,
    message: string,
};

export type Employee = {
	id: number,
	number: number,
	username: string,
	password: string,
	firstname: string,
	lastname: string,
	cellphone: string,
	homephone: string,
	email: string,
	managerid: number,
	accesslevel: number,
	timesheetrequired: boolean,
	overtimeeligible: boolean,
	tabnavigateot: boolean,
	emailexpensecopy: boolean,
	activeemployee: boolean,
	ientertimedata: boolean,
	numtimesheetsummaries: number,
	numexpensesummaries: number,
	numdefaulttimerows: number,
	contractor: boolean,
};