import type { Metadata } from "next";
import "./globals.css";
import Providers from "./components/providers";
import AppBar from "./components/app-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppBar/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
